/**
 * Contract test placeholder.
 *
 * GOAL (once wired): validate that this app's API request/response shapes
 * (and/or the MSW mock handlers in src/mocks/handlers.js) conform to the
 * Django backend's published OpenAPI schema, `contract/openapi.yaml`
 * (generated by `itse500-django` via drf-spectacular — see that repo's
 * `contract` CI job). Django is the single source of truth for the contract
 * per docs/../ci-test-conventions.md.
 *
 * STATUS: the schema is not published/checked-in yet (no
 * `contract/openapi.yaml` exists in itse500-django as of this writing), and
 * this React app does not call any Django endpoint yet either. Faking a
 * validation against a schema that doesn't exist would be worse than no test
 * — so this suite SKIPS itself until a real schema file is available, rather
 * than asserting against fabricated expectations.
 *
 * TODO (when the schema is published):
 *   1. Vendor or fetch the Django-generated `contract/openapi.yaml` into this
 *      repo (e.g. a `contract/` directory, path below, kept in sync via CI
 *      artifact download or a git submodule — match whatever the other two
 *      repos land on).
 *   2. Add a schema-validation library (e.g. `ajv` + an OpenAPI-to-JSONSchema
 *      step, or `openapi-request-validator` / `openapi-response-validator`).
 *   3. For each Django endpoint this app actually calls, assert:
 *ỗ        - the request body/query this app sends matches the schema's
 *          requestBody/parameters for that operation, and
 *        - the response shape the app expects (and the MSW handler mocks)
 *          matches the schema's response schema for that operation.
 *   4. Consider codegen instead of hand-written checks: generate a typed
 *      client via `openapi-typescript` from the same schema (per
 *      ci-test-conventions.md §3) and let type-checking do part of this job.
 */

const fs = require('fs');
const path = require('path');

// Configurable so CI (or a future local run) can point this at wherever the
// contract lands without editing this file.
const CONTRACT_SCHEMA_PATH =
  process.env.OPENAPI_CONTRACT_PATH ||
  path.resolve(__dirname, '../../../contract/openapi.yaml');

const schemaExists = fs.existsSync(CONTRACT_SCHEMA_PATH);

describe('API contract (Django OpenAPI schema)', () => {
  (schemaExists ? test : test.skip)(
    'app request/response shapes conform to contract/openapi.yaml',
    () => {
      // Intentionally left as a TODO harness — see file header. Do not add
      // fabricated assertions here; implement real validation once the
      // schema is published and at least one real endpoint call exists.
      throw new Error(
        'Contract schema found at ' +
          CONTRACT_SCHEMA_PATH +
          ' but no validation is implemented yet — see TODO in this file.'
      );
    }
  );

  if (!schemaExists) {
    test('contract schema not yet published (expected for now)', () => {
      expect(schemaExists).toBe(false);
    });
  }
});
