/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth_api/health/": {
    /**
     * Health check
     * @description Report server liveness with a simple JSON payload and 200 status.
     */
    get: operations["v1_auth_api_health_retrieve"];
  };
  "/api/v1/auth_api/login/": {
    /**
     * Login with identifier + password
     * @description Authenticate a user and return JWT tokens plus initial sync payload.
     * Accepts identifier (email/username) and user_password/password. Returns 200
     * with access/refresh tokens, conversations, and attachments on success.
     * Returns 401 for invalid credentials, 403 if user is inactive/locked, or 400/500 otherwise.
     */
    post: operations["v1_auth_api_login_create"];
  };
  "/api/v1/auth_api/logout/": {
    /**
     * Logout (client discards tokens)
     * @description Invalidate the current session and blacklist the refresh token if supplied.
     * Returns a 200 response with a brief message. Requires a valid JWT and authenticated user.
     */
    post: operations["v1_auth_api_logout_create"];
  };
  "/api/v1/auth_api/oauth/result/{state_value}/": {
    /**
     * Fetch OAuth result by state
     * @description Fetch the stored OAuth result payload for the given state (one-time).
     * Returns 202 if the result isn't ready yet, 410 if already retrieved, 404 if
     * the state is unknown, and 200 with the payload on success.
     */
    get: operations["v1_auth_api_oauth_result_retrieve"];
  };
  "/api/v1/auth_api/otp-login/": {
    /**
     * Login with OTP (deprecated)
     * @description Deprecated: OTP-based login is disabled in this release. Always returns 410 Gone.
     */
    post: operations["v1_auth_api_otp_login_create"];
  };
  "/api/v1/auth_api/register/": {
    /**
     * Register account
     * @description Create a new account or reconcile existing identity; returns JWTs and initial sync.
     */
    post: operations["v1_auth_api_register_create"];
  };
  "/api/v1/auth_api/set-password-after-email-verify/": {
    /**
     * Set password after email verify
     * @description Set/reset the account password after email verification.
     *
     * Expects JSON body with:
     * - email: string; must match the authenticated user's email
     * - password: string; client-side sha256(raw)
     *
     * On success, stores a salted backend hash and returns 200 with a message.
     * May return 400 if data is invalid or email not verified; 404 if user not found;
     * 401 if JWT is missing/invalid.
     */
    post: operations["v1_auth_api_set_password_after_email_verify_create"];
  };
  "/api/v1/auth_api/token/refresh/": {
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["v1_auth_api_token_refresh_create"];
  };
  "/api/v1/auth_api/verify-email-pin/": {
    /**
     * Verify email PIN
     * @description Verify the 5-digit email PIN for the authenticated user.
     *
     * Expects JSON body with:
     * - email: string; must match the authenticated user's email
     * - pin: string; 5-digit code
     *
     * Returns 200 with a success message on valid PIN; 400 for invalid/expired PIN;
     * 404 if the user is not found; 401 if JWT is missing/invalid.
     */
    post: operations["v1_auth_api_verify_email_pin_create"];
  };
  "/api/v1/chat_api/conversations/": {
    /** @description List the caller's own conversations, or create a new one owned by the caller. */
    get: operations["v1_chat_api_conversations_list"];
    /** @description List the caller's own conversations, or create a new one owned by the caller. */
    post: operations["v1_chat_api_conversations_create"];
  };
  "/api/v1/chat_api/conversations/{conversation_id}/": {
    /**
     * @description Retrieve/update/delete a conversation owned by the caller.
     *
     * Uses a user-scoped queryset so another user's conversation resolves to 404
     * (never 403) -- this avoids leaking whether the resource exists at all.
     */
    get: operations["v1_chat_api_conversations_retrieve"];
    /**
     * @description Retrieve/update/delete a conversation owned by the caller.
     *
     * Uses a user-scoped queryset so another user's conversation resolves to 404
     * (never 403) -- this avoids leaking whether the resource exists at all.
     */
    put: operations["v1_chat_api_conversations_update"];
    /**
     * @description Retrieve/update/delete a conversation owned by the caller.
     *
     * Uses a user-scoped queryset so another user's conversation resolves to 404
     * (never 403) -- this avoids leaking whether the resource exists at all.
     */
    delete: operations["v1_chat_api_conversations_destroy"];
    /**
     * @description Retrieve/update/delete a conversation owned by the caller.
     *
     * Uses a user-scoped queryset so another user's conversation resolves to 404
     * (never 403) -- this avoids leaking whether the resource exists at all.
     */
    patch: operations["v1_chat_api_conversations_partial_update"];
  };
  "/api/v1/chat_api/conversations/{conversation_id}/messages/": {
    /**
     * @description List or create messages within a conversation owned by the caller.
     *
     * The parent conversation is resolved with a user-scoped lookup, so a missing
     * OR non-owned conversation both yield 404 (covers the cross-user case without
     * revealing existence of another user's conversation).
     */
    get: operations["v1_chat_api_conversations_messages_list"];
    /**
     * @description List or create messages within a conversation owned by the caller.
     *
     * The parent conversation is resolved with a user-scoped lookup, so a missing
     * OR non-owned conversation both yield 404 (covers the cross-user case without
     * revealing existence of another user's conversation).
     */
    post: operations["v1_chat_api_conversations_messages_create"];
  };
  "/api/v1/chat_api/conversations/{conversation_id}/messages/{message_id}/attachments/": {
    /**
     * @description List or upload attachments belonging to a message owned by the caller.
     *
     * The parent message is resolved with a user-scoped lookup (through its
     * conversation's owner), so a missing OR non-owned message/conversation both
     * yield 404 -- never leaking existence of another user's data.
     *
     * Uses a dedicated `AttachmentUploadSerializer` for this endpoint only; the
     * `user_mang.serializers.AttachmentSerializer` used by `UnifiedSyncView` is
     * untouched.
     */
    get: operations["v1_chat_api_conversations_messages_attachments_list"];
    /**
     * @description List or upload attachments belonging to a message owned by the caller.
     *
     * The parent message is resolved with a user-scoped lookup (through its
     * conversation's owner), so a missing OR non-owned message/conversation both
     * yield 404 -- never leaking existence of another user's data.
     *
     * Uses a dedicated `AttachmentUploadSerializer` for this endpoint only; the
     * `user_mang.serializers.AttachmentSerializer` used by `UnifiedSyncView` is
     * untouched.
     */
    post: operations["v1_chat_api_conversations_messages_attachments_create"];
  };
  "/api/v1/crypto_api/umk/": {
    /**
     * Get caller UMK
     * @description Return the caller's User Master Key metadata + base64 value, or {exists: false} if not yet provisioned.
     */
    get: operations["v1_crypto_api_umk_retrieve"];
    /**
     * Provision caller UMK
     * @description Provision the UMK once. Reject with 409 if already provisioned (rotation not yet supported).
     */
    post: operations["v1_crypto_api_umk_create"];
  };
  "/api/v1/user_mang/me/": {
    /**
     * Unified sync (fetch profile/chat)
     * @description GET
     *
     * Returns a nested payload containing `profile` and/or `chat` depending on flags.
     *
     * Response shape (high level):
     *     {
     *         "user_id": <uuid>,
     *         "is_new": <bool>,
     *         "temp_id": <str|null>,
     *         "profile": { ... } ,          # present when profile=true or by default
     *         "chat": {                     # present when chat=true or by default
     *             "conversations": [...],
     *             "messages": [...],
     *             "message_request": [...],
     *             "message_response": [...],
     *             "message_output": [...],
     *             "attachments": [...]
     *         }
     *     }
     *
     * Notes / implementation details:
     * - Serializers: when available the view uses `FullProfileSerializer` and `FullChatSerializer` to produce the
     *   canonical output. If serializers fail the view falls back to minimal manual assembly.
     * - Attachments returned in `chat.attachments` always include a `user_id` field (derived from the related
     *   message) to make ownership explicit for clients.
     *
     * Example Request:
     *     GET /api/v1/unified-sync/?user_id=123e4567-e89b-12d3-a456-426614174000&profile=true&chat=true
     *
     * Example Response (simplified):
     *     {
     *         "user_id": "123e4567-e89b-12d3-a456-426614174000",
     *         "is_new": false,
     *         "temp_id": null,
     *         "profile": {
     *             "user_id": "123e4567-e89b-12d3-a456-426614174000",
     *             "username": "john_doe",
     *             "email": "john@example.com",
     *             "is_visitor": false,
     *             "is_active": true,
     *             "is_archived": false
     *         },
     *         "chat": {
     *             "conversations": [
     *                 {
     *                     "conversation_id": "c1",
     *                     "title": "My Conversation",
     *                     "messages": [ {"message_id": "m1", "content": "Hello!"} ]
     *                 }
     *             ],
     *             "messages": [ {"message_id": "m1", "content": "Hello!"} ],
     *             "attachments": [
     *                 {
     *                     "id": 1,
     *                     "type": "image",
     *                     "file_path": "/media/attachments/1.png",
     *                     "user_id": "123e4567-e89b-12d3-a456-426614174000"
     *                 }
     *             ]
     *         }
     *     }
     */
    get: operations["v1_user_mang_me_retrieve"];
    /**
     * Unified upsert (profile/chat)
     * @description Upsert profile and chat model lists atomically; returns summary/errors and canonical payload.
     */
    post: operations["v1_user_mang_me_create"];
    /**
     * Delete or archive user data
     * @description DELETE
     *
     * Delete or archive a user's profile and/or chat data.
     *
     * Important behavior changes:
     *     - The ``action`` parameter is now restricted to "delete" or "archive". Other values are rejected.
     *     - On any successful delete or archive operation this endpoint will always generate BOTH a CSV and a
     *       PDF export of the user's data.
     *     - Exports are saved under MEDIA_ROOT/exports/<user_id> and emailed to the user's verified address when
     *       available.
     *     - If the caller provides ``download_now`` (truthy: 1/true/yes) the view will zip the CSV+PDF and
     *       immediately return the zip file as a FileResponse. If ``download_now`` is falsy the files are kept on
     *       disk and the response will include URLs the client can use to download them.
     *
     * Parameters (body or query):
     *     - action: "delete" | "archive"  (required)
     *     - profile: true/false
     *     - chat: true/false
     *     - download_now: true/false or 1/0 — when true return a zip (csv+pdf) immediately; when false save and
     *       return URLs instead
     *     - reason: optional string for audit logs
     *
     * Returns (examples):
     *
     * Example Request (delete + return URLs):
     *     DELETE /api/v1/unified-sync/
     *     {
     *         "user_id": "123e4567-e89b-12d3-a456-426614174000",
     *         "action": "delete",
     *         "profile": true,
     *         "chat": true,
     *         "download_now": false
     *     }
     *
     * Example Response (delete, saved exports):
     *     HTTP 200
     *     {
     *         "message": "User and all related data deleted successfully",
     *         "deleted": { "attachments": 2, "messages": 5, "conversations": 1, "tokens": 1, "user": 1 },
     *         "export_urls": {
     *             "csv": "https://example.com/media/exports/<user_id>/user_export_20250829123000.csv",
     *             "pdf": "https://example.com/media/exports/<user_id>/user_export_20250829123000.pdf"
     *         },
     *         "profile": { /* FullProfileSerializer output or minimal fallback *\/ },
     *         "chat": { /* FullChatSerializer output or minimal fallback *\/ }
     *     }
     *
     * Example Request (archive + immediate download):
     *     DELETE /api/v1/unified-sync/
     *     {
     *         "user_id": "123e4567-e89b-12d3-a456-426614174000",
     *         "action": "archive",
     *         "profile": true,
     *         "download_now": true
     *     }
     *
     * Example Response (archive, immediate zip):
     *     HTTP 200
     *     (A FileResponse serving an attachment named "user_export_<user_id>.zip" containing both CSV and PDF)
     *
     * Notes:
     *     - Exporting and emailing are best-effort. Failures while creating or sending exports are logged and do
     *       not prevent the delete/archive from completing.
     *     - The response will include ``export_urls`` when files are saved and not directly returned.
     */
    delete: operations["v1_user_mang_me_destroy"];
    /**
     * Partial profile update
     * @description Authenticated partial update for profile fields (me endpoint style).
     */
    patch: operations["v1_user_mang_me_partial_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description Serialize an artifact attached to a message (image/pdf/embedding/etc.).
     * - Accepts 'id' in payload as an alias to attachment_id to match the UnifiedSyncView.
     * - user_id is read-only and the view should call serializer.save(user=user) on create.
     */
    Attachment: {
      id?: string;
      /** Format: uuid */
      attachment_id: string;
      user_id: string;
      /** Format: uuid */
      conversation_id: string;
      /** Format: uuid */
      message_id: string;
      type: string;
      mime_type?: string | null;
      /** @description Server-side storage path or external URL */
      file_path?: string | null;
      /** Format: uri */
      encrypted_blob?: string | null;
      /** Format: int64 */
      size_bytes?: number | null;
      /** Format: int64 */
      width?: number | null;
      /** Format: int64 */
      height?: number | null;
      sha256?: string | null;
      is_encrypted?: boolean;
      enc_algo?: string | null;
      iv_base64?: string | null;
      key_ref?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    AttachmentDoc: {
      attachment_id?: string;
      message_id?: string;
      url?: string;
    };
    /**
     * @description Serialize an artifact attached to a message (image/pdf/embedding/etc.).
     * - Accepts 'id' in payload as an alias to attachment_id to match the UnifiedSyncView.
     * - user_id is read-only and the view should call serializer.save(user=user) on create.
     */
    AttachmentRequest: {
      id?: string;
      /** Format: uuid */
      conversation_id: string;
      /** Format: uuid */
      message_id: string;
      type: string;
      mime_type?: string | null;
      /** @description Server-side storage path or external URL */
      file_path?: string | null;
      /** Format: binary */
      encrypted_blob?: string | null;
      /** Format: int64 */
      size_bytes?: number | null;
      /** Format: int64 */
      width?: number | null;
      /** Format: int64 */
      height?: number | null;
      sha256?: string | null;
      is_encrypted?: boolean;
      enc_algo?: string | null;
      iv_base64?: string | null;
      key_ref?: string | null;
    };
    /**
     * @description Write-side Attachment serializer for the message-scoped upload/list endpoint.
     *
     * Dedicated to this endpoint only -- does NOT replace or alias
     * `user_mang.serializers.AttachmentSerializer`, which the UnifiedSyncView still
     * uses unchanged. The parent message is supplied by the view (from the URL),
     * and `size_bytes`/`sha256` are computed server-side from the uploaded bytes.
     */
    AttachmentUpload: {
      /** Format: uuid */
      attachment_id: string;
      /** Format: uuid */
      message_id: string;
      type: string;
      mime_type?: string | null;
      /**
       * Format: uri
       * @description Encrypted ciphertext blob uploaded by client
       */
      encrypted_blob?: string | null;
      size_bytes: number | null;
      sha256: string | null;
      is_encrypted?: boolean;
      enc_algo?: string | null;
      iv_base64?: string | null;
      key_ref?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    /**
     * @description Write-side Attachment serializer for the message-scoped upload/list endpoint.
     *
     * Dedicated to this endpoint only -- does NOT replace or alias
     * `user_mang.serializers.AttachmentSerializer`, which the UnifiedSyncView still
     * uses unchanged. The parent message is supplied by the view (from the URL),
     * and `size_bytes`/`sha256` are computed server-side from the uploaded bytes.
     */
    AttachmentUploadRequest: {
      type: string;
      mime_type?: string | null;
      /**
       * Format: binary
       * @description Encrypted ciphertext blob uploaded by client
       */
      encrypted_blob?: string | null;
      is_encrypted?: boolean;
      enc_algo?: string | null;
      iv_base64?: string | null;
      key_ref?: string | null;
    };
    /**
     * @description Serialize a conversation with nested messages (read-only).
     * For writes, clients send a flat conversation object; messages are synced separately.
     */
    Conversation: {
      /** Format: uuid */
      conversation_id: string;
      /** Format: uuid */
      user_id: string;
      title?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      local_only?: boolean;
      messages: readonly components["schemas"]["Message"][];
    };
    ConversationDoc: {
      conversation_id: string;
      title?: string | null;
      /** Format: date-time */
      updated_at?: string;
      messages: components["schemas"]["MessageDoc"][];
    };
    /**
     * @description Serialize a conversation with nested messages (read-only).
     * For writes, clients send a flat conversation object; messages are synced separately.
     */
    ConversationRequest: {
      title?: string | null;
      local_only?: boolean;
    };
    DeprecatedEndpointResponse: {
      detail: string;
    };
    EmailPinVerifyRequestRequest: {
      /** Format: email */
      email: string;
      pin: string;
    };
    EmailPinVerifyResponse: {
      message: string;
    };
    /**
     * @description Composite serializer that returns the complete chat payload for a user.
     * Fields:
     *     - conversations: ConversationSerializer (with nested messages)
     *     - messages: MessageSerializer (flat list)
     *     - message_request: MessageRequestSerializer
     *     - message_response: MessageResponseSerializer
     *     - message_output: MessageOutputSerializer
     *     - attachments: AttachmentSerializer
     *
     * This serializer is intentionally a non-model `Serializer` since it aggregates
     * multiple querysets and models into a single response shape used by
     * `UnifiedSyncView.get`.
     */
    FullChat: {
      conversations: readonly components["schemas"]["Conversation"][];
      messages: readonly components["schemas"]["Message"][];
      message_request: readonly components["schemas"]["MessageRequest"][];
      message_response: readonly components["schemas"]["MessageResponse"][];
      message_output: readonly components["schemas"]["MessageOutput"][];
      attachments: readonly components["schemas"]["Attachment"][];
    };
    /**
     * @description Full profile serializer that exposes most editable user fields.
     * This allows the UnifiedSyncView to upsert the complete user object.
     * Sensitive fields like `is_superuser`, `groups`, and `user_permissions` are intentionally omitted.
     */
    FullProfile: {
      /** Format: uuid */
      user_id: string;
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      first_name?: string;
      last_name?: string;
      /** Format: email */
      email: string;
      phone_number?: string | null;
      /** Format: date-time */
      last_modified: string;
      devices_id?: unknown;
      temp_id?: string | null;
      related_devices?: unknown;
      /**
       * Format: date-time
       * @description When the PIN was generated
       */
      email_pin_created?: string | null;
      /** @description Has the user verified their email? */
      email_verified?: boolean;
      /** @description Is the user account archived? */
      is_archived?: boolean;
      /** @description Account created / linked via Google OAuth */
      is_google_user?: boolean;
      /** @description Account created / linked via OpenRouter OAuth */
      is_openrouter_user?: boolean;
      /** @description Account created / linked via Microsoft OAuth */
      is_microsoft_user?: boolean;
      /** @description Account created / linked via GitHub OAuth */
      is_github_user?: boolean;
      /**
       * Active
       * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
       */
      is_active?: boolean;
      /**
       * Staff status
       * @description Designates whether the user can log into this admin site.
       */
      is_staff?: boolean;
    };
    /**
     * @description Full profile serializer that exposes most editable user fields.
     * This allows the UnifiedSyncView to upsert the complete user object.
     * Sensitive fields like `is_superuser`, `groups`, and `user_permissions` are intentionally omitted.
     */
    FullProfileRequest: {
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      first_name?: string;
      last_name?: string;
      /** Format: email */
      email: string;
      user_password?: string;
      phone_number?: string | null;
      devices_id?: unknown;
      temp_id?: string | null;
      related_devices?: unknown;
      /**
       * Format: date-time
       * @description When the PIN was generated
       */
      email_pin_created?: string | null;
      /** @description Has the user verified their email? */
      email_verified?: boolean;
      /** @description Is the user account archived? */
      is_archived?: boolean;
      /** @description Account created / linked via Google OAuth */
      is_google_user?: boolean;
      /** @description Account created / linked via OpenRouter OAuth */
      is_openrouter_user?: boolean;
      /** @description Account created / linked via Microsoft OAuth */
      is_microsoft_user?: boolean;
      /** @description Account created / linked via GitHub OAuth */
      is_github_user?: boolean;
      /**
       * Active
       * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
       */
      is_active?: boolean;
      /**
       * Staff status
       * @description Designates whether the user can log into this admin site.
       */
      is_staff?: boolean;
    };
    HealthCheckResponse: {
      status: string;
      message: string;
    };
    LoginRequest: {
      identifier?: string;
      email?: string;
      username?: string;
      user_password?: string;
    };
    LoginResponse: {
      message: string;
      user_id: string;
      access_token: string;
      refresh_token: string;
      email_verified: boolean;
      conversations: components["schemas"]["ConversationDoc"][];
      attachments: components["schemas"]["AttachmentDoc"][];
    };
    LogoutRequestRequest: {
      /** @description Refresh token to blacklist (optional; may also be supplied via header/cookie). */
      refresh_token?: string;
    };
    LogoutResponse: {
      detail: string;
    };
    /**
     * @description Serialize a chat message.
     * - Write: accept PKs for `request_id`, `response_id`, `output_id`, `conversation_id`.
     * - Read: also include nested `request`, `response`, `output` for convenience.
     * - File fields (`img_Url`, `doc_url`) are rendered as URLs.
     */
    Message: {
      /** Format: uuid */
      message_id: string;
      /** Format: uuid */
      user_id: string;
      /** Format: uuid */
      conversation_id: string;
      /** Format: uuid */
      request_id?: string | null;
      response_id?: string | null;
      output_id?: number | null;
      /** Format: date-time */
      timestamp: string;
      status?: components["schemas"]["StatusEnum"];
      vote?: boolean | null;
      has_image?: boolean;
      /** Format: uri */
      img_Url?: string | null;
      metadata?: unknown;
      has_embedding?: boolean;
      has_document?: boolean;
      /** Format: uri */
      doc_url?: string | null;
      request: components["schemas"]["MessageRequest"];
      response: components["schemas"]["MessageResponse"];
      output: components["schemas"]["MessageOutput"];
    };
    MessageDoc: {
      message_id: string;
      /** Format: date-time */
      timestamp: string;
      has_image?: boolean;
      has_document?: boolean;
    };
    /**
     * @description Serialize a normalized *output item* of a response (e.g., final message text).
     * Note: model has an implicit AutoField `id`. `output_id` is a provider-side identifier.
     */
    MessageOutput: {
      id: number;
      output_type?: string | null;
      output_id?: string | null;
      output_status?: string | null;
      output_role?: string | null;
      output_content_type?: string | null;
      output_content_text?: string | null;
      output_content_annotations?: string | null;
    };
    /**
     * @description Serialize a normalized *output item* of a response (e.g., final message text).
     * Note: model has an implicit AutoField `id`. `output_id` is a provider-side identifier.
     */
    MessageOutputRequest: {
      output_type?: string | null;
      output_id?: string | null;
      output_status?: string | null;
      output_role?: string | null;
      output_content_type?: string | null;
      output_content_text?: string | null;
      output_content_annotations?: string | null;
    };
    /**
     * @description Serialize a single model generation *request* (the user's prompt/config).
     * Primary key: `request_id` (UUID).
     * Used both to return request details (GET) and to upsert them (POST).
     */
    MessageRequest: {
      /** Format: uuid */
      request_id: string;
      request_model?: string | null;
      request_input?: string | null;
      request_system_role?: string | null;
      request_system_content?: string | null;
      request_system_prompt?: string | null;
      request_user_structured_output?: boolean | null;
      request_structured_schema?: string | null;
      request_user_role?: string | null;
      request_user_content?: string | null;
      /** Format: double */
      request_min_p?: number | null;
      /** Format: double */
      request_temperature?: number | null;
      /** Format: double */
      request_top_p?: number | null;
      /** Format: int64 */
      request_n?: number | null;
      /** Format: int64 */
      request_top_k?: number | null;
      request_stream?: boolean;
      request_stop?: string | null;
      /** Format: int64 */
      request_max_tokens?: number | null;
      /** Format: double */
      repeat_penalty?: number | null;
    };
    /**
     * @description Serialize a single model generation *request* (the user's prompt/config).
     * Primary key: `request_id` (UUID).
     * Used both to return request details (GET) and to upsert them (POST).
     */
    MessageRequestRequest: {
      request_model?: string | null;
      request_input?: string | null;
      request_system_role?: string | null;
      request_system_content?: string | null;
      request_system_prompt?: string | null;
      request_user_structured_output?: boolean | null;
      request_structured_schema?: string | null;
      request_user_role?: string | null;
      request_user_content?: string | null;
      /** Format: double */
      request_min_p?: number | null;
      /** Format: double */
      request_temperature?: number | null;
      /** Format: double */
      request_top_p?: number | null;
      /** Format: int64 */
      request_n?: number | null;
      /** Format: int64 */
      request_top_k?: number | null;
      request_stream?: boolean;
      request_stop?: string | null;
      /** Format: int64 */
      request_max_tokens?: number | null;
      /** Format: double */
      repeat_penalty?: number | null;
    };
    /**
     * @description Serialize a provider/model *response* aggregate (metadata + usage + settings).
     * Primary key: `response_id` (string).
     */
    MessageResponse: {
      response_id: string;
      object?: string | null;
      /** Format: date-time */
      created_at?: string | null;
      status?: string | null;
      error?: string | null;
      model_name?: string | null;
      parallel_tool_calls?: boolean;
      previous_response_id?: string | null;
      instructions?: string | null;
      reasoning_effort?: string | null;
      reasoning_summary?: string | null;
      store?: boolean;
      /** Format: double */
      temperature?: number | null;
      text_format_type?: string | null;
      tool_choice?: string | null;
      tools?: string | null;
      /** Format: double */
      top_p?: number | null;
      truncation?: string | null;
      /** Format: int64 */
      usage_input_tokens?: number | null;
      /** Format: int64 */
      usage_output_tokens?: number | null;
      /** Format: int64 */
      usage_total_tokens?: number | null;
      user: string | null;
      metadata?: unknown;
      incomplete_details?: string | null;
      /** Format: int64 */
      max_output_tokens?: number | null;
    };
    /**
     * @description Serialize a provider/model *response* aggregate (metadata + usage + settings).
     * Primary key: `response_id` (string).
     */
    MessageResponseRequest: {
      response_id: string;
      object?: string | null;
      /** Format: date-time */
      created_at?: string | null;
      status?: string | null;
      error?: string | null;
      model_name?: string | null;
      parallel_tool_calls?: boolean;
      previous_response_id?: string | null;
      instructions?: string | null;
      reasoning_effort?: string | null;
      reasoning_summary?: string | null;
      store?: boolean;
      /** Format: double */
      temperature?: number | null;
      text_format_type?: string | null;
      tool_choice?: string | null;
      tools?: string | null;
      /** Format: double */
      top_p?: number | null;
      truncation?: string | null;
      /** Format: int64 */
      usage_input_tokens?: number | null;
      /** Format: int64 */
      usage_output_tokens?: number | null;
      /** Format: int64 */
      usage_total_tokens?: number | null;
      metadata?: unknown;
      incomplete_details?: string | null;
      /** Format: int64 */
      max_output_tokens?: number | null;
    };
    /**
     * @description Write-side Message serializer for the nested conversation messages endpoint.
     *
     * The conversation is supplied by the view (from the URL), not the client, so
     * `conversation_id` is not required in the request body.
     */
    MessageWrite: {
      /** Format: uuid */
      message_id: string;
      /** Format: uuid */
      user_id: string;
      /** Format: uuid */
      conversation_id?: string;
      /** Format: uuid */
      request_id?: string | null;
      response_id?: string | null;
      output_id?: number | null;
      /** Format: date-time */
      timestamp: string;
      status?: components["schemas"]["StatusEnum"];
      vote?: boolean | null;
      has_image?: boolean;
      /** Format: uri */
      img_Url?: string | null;
      metadata?: unknown;
      has_embedding?: boolean;
      has_document?: boolean;
      /** Format: uri */
      doc_url?: string | null;
      request: components["schemas"]["MessageRequest"];
      response: components["schemas"]["MessageResponse"];
      output: components["schemas"]["MessageOutput"];
    };
    /**
     * @description Write-side Message serializer for the nested conversation messages endpoint.
     *
     * The conversation is supplied by the view (from the URL), not the client, so
     * `conversation_id` is not required in the request body.
     */
    MessageWriteRequest: {
      /** Format: uuid */
      conversation_id?: string;
      /** Format: uuid */
      request_id?: string | null;
      response_id?: string | null;
      output_id?: number | null;
      status?: components["schemas"]["StatusEnum"];
      vote?: boolean | null;
      has_image?: boolean;
      /** Format: binary */
      img_Url?: string | null;
      metadata?: unknown;
      has_embedding?: boolean;
      has_document?: boolean;
      /** Format: binary */
      doc_url?: string | null;
    };
    OAuthCallbackResponse: {
      message: string;
      user_id: string;
      username?: string | null;
      access_token: string;
      refresh_token: string;
      provider_scope?: string | null;
      provider_expires_at?: string | null;
      provider_access_token?: string | null;
      provider_refresh_token?: string | null;
      provider_token_type?: string | null;
      id_token?: string | null;
      /** Format: email */
      email?: string | null;
      email_verified?: boolean;
      is_google_user?: boolean;
      is_openrouter_user?: boolean;
      is_github_user?: boolean;
      is_ms_user?: boolean;
    };
    PaginatedAttachmentUploadList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["AttachmentUpload"][];
    };
    PaginatedConversationList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["Conversation"][];
    };
    PaginatedMessageList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["Message"][];
    };
    /**
     * @description Serialize a conversation with nested messages (read-only).
     * For writes, clients send a flat conversation object; messages are synced separately.
     */
    PatchedConversationRequest: {
      title?: string | null;
      local_only?: boolean;
    };
    /**
     * @description Safe profile serializer for client-driven profile updates.
     * Whitelisted writable fields: username, email, phone_number, biometric_enabled.
     * Sensitive fields (email_verified, is_staff, is_superuser, user_password, related_devices, etc.)
     * are intentionally excluded.
     */
    PatchedProfileRequest: {
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username?: string;
      /** Format: email */
      email?: string;
      phone_number?: string | null;
      biometric_enabled?: boolean;
    };
    /**
     * @description Safe profile serializer for client-driven profile updates.
     * Whitelisted writable fields: username, email, phone_number, biometric_enabled.
     * Sensitive fields (email_verified, is_staff, is_superuser, user_password, related_devices, etc.)
     * are intentionally excluded.
     */
    Profile: {
      /** Format: uuid */
      user_id: string;
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      /** Format: email */
      email: string;
      phone_number?: string | null;
      biometric_enabled?: boolean;
    };
    RegisterRequest: {
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      /** Format: email */
      email: string;
      user_password?: string;
    };
    RegisterResponse: {
      message: string;
      user_id: string;
      access_token: string;
      refresh_token: string;
      /** Format: email */
      email: string;
      onboarding: boolean;
      conversations: components["schemas"]["ConversationDoc"][];
      temp_id?: string | null;
      device_id?: string | null;
      related_devices?: string[];
    };
    SetPasswordAfterEmailVerifyRequestRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    SetPasswordAfterEmailVerifyResponse: {
      message: string;
    };
    /**
     * @description * `pending` - pending
     * * `streaming` - streaming
     * * `complete` - complete
     * * `error` - error
     * @enum {string}
     */
    StatusEnum: "pending" | "streaming" | "complete" | "error";
    TokenRefresh: {
      access: string;
      refresh: string;
    };
    TokenRefreshRequest: {
      refresh: string;
    };
    UMKErrorResponse: {
      error: string;
    };
    /** @description GET response shape when the caller's UMK exists (UserKeyMaterial fields + exists=True). */
    UMKGetResponse: {
      /** @description Owning user id */
      user: number;
      umk_b64: string;
      version: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** @default true */
      exists?: boolean;
    };
    /** @description POST request body: optionally client-supplied 32-byte key, base64-encoded. */
    UMKProvisionRequestRequest: {
      /** @description Optional client-provided 32-byte key, base64-encoded. If omitted, the server generates one. */
      umk_b64?: string;
    };
    /** @description 201 response after provisioning: the created UserKeyMaterial record. */
    UMKProvisionResponse: {
      /** @description Owning user id */
      user: number;
      umk_b64: string;
      version: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @description DELETE /unified-sync/ response: delete/archive summary + optional export URLs. */
    UnifiedSyncDeleteResponse: {
      message: string;
      deleted?: components["schemas"]["UnifiedSyncDeleteStats"];
      archived?: components["schemas"]["UnifiedSyncDeleteStats"];
      export_urls?: {
        [key: string]: string;
      };
      profile?: components["schemas"]["FullProfile"];
      chat?: components["schemas"]["FullChat"];
    };
    UnifiedSyncDeleteStats: {
      attachments?: number;
      messages?: number;
      conversations?: number;
      tokens?: number;
      user?: number;
    };
    /** @description GET /unified-sync/ — nested profile/chat payload (shape depends on profile=/chat= flags). */
    UnifiedSyncGetResponse: {
      user_id: string | null;
      is_new: boolean;
      temp_id?: string | null;
      profile?: components["schemas"]["FullProfile"];
      chat?: components["schemas"]["FullChat"];
    };
    /** @description PATCH /unified-sync/ response: the updated profile. */
    UnifiedSyncPatchResponse: {
      profile: components["schemas"]["Profile"];
    };
    /** @description POST /unified-sync/ request body: optional profile + chat model lists to upsert. */
    UnifiedSyncPostRequestRequest: {
      profile?: components["schemas"]["FullProfileRequest"];
      conversations?: components["schemas"]["ConversationRequest"][];
      messages?: components["schemas"]["MessageRequest"][];
      message_requests?: components["schemas"]["MessageRequestRequest"][];
      message_responses?: components["schemas"]["MessageResponseRequest"][];
      message_outputs?: components["schemas"]["MessageOutputRequest"][];
      attachments?: components["schemas"]["AttachmentRequest"][];
    };
    /** @description POST /unified-sync/ response: upsert summary/errors + canonical profile/chat payload. */
    UnifiedSyncPostResponse: {
      summary: components["schemas"]["UnifiedSyncUpsertSummary"];
      errors?: {
        [key: string]: unknown[];
      };
      user_id: string | null;
      temp_id?: string | null;
      profile?: components["schemas"]["FullProfile"];
      chat?: components["schemas"]["FullChat"];
    };
    /** @description Per-model created/updated counters returned by POST /unified-sync/. */
    UnifiedSyncUpsertSummary: {
      profile_updated?: boolean;
      conversations_created?: number;
      conversations_updated?: number;
      messages_created?: number;
      messages_updated?: number;
      requests_created?: number;
      requests_updated?: number;
      responses_created?: number;
      responses_updated?: number;
      outputs_created?: number;
      outputs_updated?: number;
      attachments_created?: number;
      attachments_updated?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Health check
   * @description Report server liveness with a simple JSON payload and 200 status.
   */
  v1_auth_api_health_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HealthCheckResponse"];
        };
      };
    };
  };
  /**
   * Login with identifier + password
   * @description Authenticate a user and return JWT tokens plus initial sync payload.
   * Accepts identifier (email/username) and user_password/password. Returns 200
   * with access/refresh tokens, conversations, and attachments on success.
   * Returns 401 for invalid credentials, 403 if user is inactive/locked, or 400/500 otherwise.
   */
  v1_auth_api_login_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
        "multipart/form-data": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        content: never;
      };
      /** @description User locked */
      403: {
        content: never;
      };
    };
  };
  /**
   * Logout (client discards tokens)
   * @description Invalidate the current session and blacklist the refresh token if supplied.
   * Returns a 200 response with a brief message. Requires a valid JWT and authenticated user.
   */
  v1_auth_api_logout_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["LogoutRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["LogoutRequestRequest"];
        "multipart/form-data": components["schemas"]["LogoutRequestRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
    };
  };
  /**
   * Fetch OAuth result by state
   * @description Fetch the stored OAuth result payload for the given state (one-time).
   * Returns 202 if the result isn't ready yet, 410 if already retrieved, 404 if
   * the state is unknown, and 200 with the payload on success.
   */
  v1_auth_api_oauth_result_retrieve: {
    parameters: {
      path: {
        /** @description State value used in OAuth */
        state_value: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["OAuthCallbackResponse"];
        };
      };
      /** @description Result not ready */
      202: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
      /** @description Already retrieved */
      410: {
        content: never;
      };
    };
  };
  /**
   * Login with OTP (deprecated)
   * @description Deprecated: OTP-based login is disabled in this release. Always returns 410 Gone.
   */
  v1_auth_api_otp_login_create: {
    responses: {
      410: {
        content: {
          "application/json": components["schemas"]["DeprecatedEndpointResponse"];
        };
      };
    };
  };
  /**
   * Register account
   * @description Create a new account or reconcile existing identity; returns JWTs and initial sync.
   */
  v1_auth_api_register_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
        "multipart/form-data": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RegisterResponse"];
        };
      };
      201: {
        content: {
          "application/json": components["schemas"]["RegisterResponse"];
        };
      };
      /** @description invalid credentials. */
      409: {
        content: never;
      };
    };
  };
  /**
   * Set password after email verify
   * @description Set/reset the account password after email verification.
   *
   * Expects JSON body with:
   * - email: string; must match the authenticated user's email
   * - password: string; client-side sha256(raw)
   *
   * On success, stores a salted backend hash and returns 200 with a message.
   * May return 400 if data is invalid or email not verified; 404 if user not found;
   * 401 if JWT is missing/invalid.
   */
  v1_auth_api_set_password_after_email_verify_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPasswordAfterEmailVerifyRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["SetPasswordAfterEmailVerifyRequestRequest"];
        "multipart/form-data": components["schemas"]["SetPasswordAfterEmailVerifyRequestRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SetPasswordAfterEmailVerifyResponse"];
        };
      };
      /** @description Invalid data or email not verified */
      400: {
        content: never;
      };
      /** @description Auth required */
      401: {
        content: never;
      };
      /** @description User not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * @description Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  v1_auth_api_token_refresh_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefreshRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
        "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  /**
   * Verify email PIN
   * @description Verify the 5-digit email PIN for the authenticated user.
   *
   * Expects JSON body with:
   * - email: string; must match the authenticated user's email
   * - pin: string; 5-digit code
   *
   * Returns 200 with a success message on valid PIN; 400 for invalid/expired PIN;
   * 404 if the user is not found; 401 if JWT is missing/invalid.
   */
  v1_auth_api_verify_email_pin_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPinVerifyRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["EmailPinVerifyRequestRequest"];
        "multipart/form-data": components["schemas"]["EmailPinVerifyRequestRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EmailPinVerifyResponse"];
        };
      };
      /** @description Invalid PIN or expired */
      400: {
        content: never;
      };
      /** @description Auth required */
      401: {
        content: never;
      };
      /** @description User not found */
      404: {
        content: never;
      };
    };
  };
  /** @description List the caller's own conversations, or create a new one owned by the caller. */
  v1_chat_api_conversations_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedConversationList"];
        };
      };
    };
  };
  /** @description List the caller's own conversations, or create a new one owned by the caller. */
  v1_chat_api_conversations_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConversationRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["ConversationRequest"];
        "multipart/form-data": components["schemas"]["ConversationRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  /**
   * @description Retrieve/update/delete a conversation owned by the caller.
   *
   * Uses a user-scoped queryset so another user's conversation resolves to 404
   * (never 403) -- this avoids leaking whether the resource exists at all.
   */
  v1_chat_api_conversations_retrieve: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  /**
   * @description Retrieve/update/delete a conversation owned by the caller.
   *
   * Uses a user-scoped queryset so another user's conversation resolves to 404
   * (never 403) -- this avoids leaking whether the resource exists at all.
   */
  v1_chat_api_conversations_update: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConversationRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["ConversationRequest"];
        "multipart/form-data": components["schemas"]["ConversationRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  /**
   * @description Retrieve/update/delete a conversation owned by the caller.
   *
   * Uses a user-scoped queryset so another user's conversation resolves to 404
   * (never 403) -- this avoids leaking whether the resource exists at all.
   */
  v1_chat_api_conversations_destroy: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * @description Retrieve/update/delete a conversation owned by the caller.
   *
   * Uses a user-scoped queryset so another user's conversation resolves to 404
   * (never 403) -- this avoids leaking whether the resource exists at all.
   */
  v1_chat_api_conversations_partial_update: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedConversationRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedConversationRequest"];
        "multipart/form-data": components["schemas"]["PatchedConversationRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
    };
  };
  /**
   * @description List or create messages within a conversation owned by the caller.
   *
   * The parent conversation is resolved with a user-scoped lookup, so a missing
   * OR non-owned conversation both yield 404 (covers the cross-user case without
   * revealing existence of another user's conversation).
   */
  v1_chat_api_conversations_messages_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      path: {
        conversation_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedMessageList"];
        };
      };
    };
  };
  /**
   * @description List or create messages within a conversation owned by the caller.
   *
   * The parent conversation is resolved with a user-scoped lookup, so a missing
   * OR non-owned conversation both yield 404 (covers the cross-user case without
   * revealing existence of another user's conversation).
   */
  v1_chat_api_conversations_messages_create: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["MessageWriteRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["MessageWriteRequest"];
        "multipart/form-data": components["schemas"]["MessageWriteRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["MessageWrite"];
        };
      };
    };
  };
  /**
   * @description List or upload attachments belonging to a message owned by the caller.
   *
   * The parent message is resolved with a user-scoped lookup (through its
   * conversation's owner), so a missing OR non-owned message/conversation both
   * yield 404 -- never leaking existence of another user's data.
   *
   * Uses a dedicated `AttachmentUploadSerializer` for this endpoint only; the
   * `user_mang.serializers.AttachmentSerializer` used by `UnifiedSyncView` is
   * untouched.
   */
  v1_chat_api_conversations_messages_attachments_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      path: {
        conversation_id: string;
        message_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedAttachmentUploadList"];
        };
      };
    };
  };
  /**
   * @description List or upload attachments belonging to a message owned by the caller.
   *
   * The parent message is resolved with a user-scoped lookup (through its
   * conversation's owner), so a missing OR non-owned message/conversation both
   * yield 404 -- never leaking existence of another user's data.
   *
   * Uses a dedicated `AttachmentUploadSerializer` for this endpoint only; the
   * `user_mang.serializers.AttachmentSerializer` used by `UnifiedSyncView` is
   * untouched.
   */
  v1_chat_api_conversations_messages_attachments_create: {
    parameters: {
      path: {
        conversation_id: string;
        message_id: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["AttachmentUploadRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentUploadRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AttachmentUpload"];
        };
      };
    };
  };
  /**
   * Get caller UMK
   * @description Return the caller's User Master Key metadata + base64 value, or {exists: false} if not yet provisioned.
   */
  v1_crypto_api_umk_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UMKGetResponse"];
        };
      };
    };
  };
  /**
   * Provision caller UMK
   * @description Provision the UMK once. Reject with 409 if already provisioned (rotation not yet supported).
   */
  v1_crypto_api_umk_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UMKProvisionRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["UMKProvisionRequestRequest"];
        "multipart/form-data": components["schemas"]["UMKProvisionRequestRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["UMKProvisionResponse"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["UMKErrorResponse"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["UMKErrorResponse"];
        };
      };
    };
  };
  /**
   * Unified sync (fetch profile/chat)
   * @description GET
   *
   * Returns a nested payload containing `profile` and/or `chat` depending on flags.
   *
   * Response shape (high level):
   *     {
   *         "user_id": <uuid>,
   *         "is_new": <bool>,
   *         "temp_id": <str|null>,
   *         "profile": { ... } ,          # present when profile=true or by default
   *         "chat": {                     # present when chat=true or by default
   *             "conversations": [...],
   *             "messages": [...],
   *             "message_request": [...],
   *             "message_response": [...],
   *             "message_output": [...],
   *             "attachments": [...]
   *         }
   *     }
   *
   * Notes / implementation details:
   * - Serializers: when available the view uses `FullProfileSerializer` and `FullChatSerializer` to produce the
   *   canonical output. If serializers fail the view falls back to minimal manual assembly.
   * - Attachments returned in `chat.attachments` always include a `user_id` field (derived from the related
   *   message) to make ownership explicit for clients.
   *
   * Example Request:
   *     GET /api/v1/unified-sync/?user_id=123e4567-e89b-12d3-a456-426614174000&profile=true&chat=true
   *
   * Example Response (simplified):
   *     {
   *         "user_id": "123e4567-e89b-12d3-a456-426614174000",
   *         "is_new": false,
   *         "temp_id": null,
   *         "profile": {
   *             "user_id": "123e4567-e89b-12d3-a456-426614174000",
   *             "username": "john_doe",
   *             "email": "john@example.com",
   *             "is_visitor": false,
   *             "is_active": true,
   *             "is_archived": false
   *         },
   *         "chat": {
   *             "conversations": [
   *                 {
   *                     "conversation_id": "c1",
   *                     "title": "My Conversation",
   *                     "messages": [ {"message_id": "m1", "content": "Hello!"} ]
   *                 }
   *             ],
   *             "messages": [ {"message_id": "m1", "content": "Hello!"} ],
   *             "attachments": [
   *                 {
   *                     "id": 1,
   *                     "type": "image",
   *                     "file_path": "/media/attachments/1.png",
   *                     "user_id": "123e4567-e89b-12d3-a456-426614174000"
   *                 }
   *             ]
   *         }
   *     }
   */
  v1_user_mang_me_retrieve: {
    parameters: {
      query?: {
        /** @description Allow unauthenticated read by UUID for GET */
        allow_public_uuid?: boolean;
        /** @description Include chat section */
        chat?: boolean;
        /** @description Associate device with user/visitor */
        device_id?: string;
        /** @description Include profile section */
        profile?: boolean;
        /** @description Visitor temp identifier (issues short-lived tokens) */
        temp_id?: string;
        /** @description User UUID (GET only, when allow_public_uuid=true) */
        user_id?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UnifiedSyncGetResponse"];
        };
      };
    };
  };
  /**
   * Unified upsert (profile/chat)
   * @description Upsert profile and chat model lists atomically; returns summary/errors and canonical payload.
   */
  v1_user_mang_me_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UnifiedSyncPostRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["UnifiedSyncPostRequestRequest"];
        "multipart/form-data": components["schemas"]["UnifiedSyncPostRequestRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UnifiedSyncPostResponse"];
        };
      };
      /** @description Validation error */
      400: {
        content: never;
      };
      /** @description Transaction failed */
      500: {
        content: never;
      };
    };
  };
  /**
   * Delete or archive user data
   * @description DELETE
   *
   * Delete or archive a user's profile and/or chat data.
   *
   * Important behavior changes:
   *     - The ``action`` parameter is now restricted to "delete" or "archive". Other values are rejected.
   *     - On any successful delete or archive operation this endpoint will always generate BOTH a CSV and a
   *       PDF export of the user's data.
   *     - Exports are saved under MEDIA_ROOT/exports/<user_id> and emailed to the user's verified address when
   *       available.
   *     - If the caller provides ``download_now`` (truthy: 1/true/yes) the view will zip the CSV+PDF and
   *       immediately return the zip file as a FileResponse. If ``download_now`` is falsy the files are kept on
   *       disk and the response will include URLs the client can use to download them.
   *
   * Parameters (body or query):
   *     - action: "delete" | "archive"  (required)
   *     - profile: true/false
   *     - chat: true/false
   *     - download_now: true/false or 1/0 — when true return a zip (csv+pdf) immediately; when false save and
   *       return URLs instead
   *     - reason: optional string for audit logs
   *
   * Returns (examples):
   *
   * Example Request (delete + return URLs):
   *     DELETE /api/v1/unified-sync/
   *     {
   *         "user_id": "123e4567-e89b-12d3-a456-426614174000",
   *         "action": "delete",
   *         "profile": true,
   *         "chat": true,
   *         "download_now": false
   *     }
   *
   * Example Response (delete, saved exports):
   *     HTTP 200
   *     {
   *         "message": "User and all related data deleted successfully",
   *         "deleted": { "attachments": 2, "messages": 5, "conversations": 1, "tokens": 1, "user": 1 },
   *         "export_urls": {
   *             "csv": "https://example.com/media/exports/<user_id>/user_export_20250829123000.csv",
   *             "pdf": "https://example.com/media/exports/<user_id>/user_export_20250829123000.pdf"
   *         },
   *         "profile": { /* FullProfileSerializer output or minimal fallback *\/ },
   *         "chat": { /* FullChatSerializer output or minimal fallback *\/ }
   *     }
   *
   * Example Request (archive + immediate download):
   *     DELETE /api/v1/unified-sync/
   *     {
   *         "user_id": "123e4567-e89b-12d3-a456-426614174000",
   *         "action": "archive",
   *         "profile": true,
   *         "download_now": true
   *     }
   *
   * Example Response (archive, immediate zip):
   *     HTTP 200
   *     (A FileResponse serving an attachment named "user_export_<user_id>.zip" containing both CSV and PDF)
   *
   * Notes:
   *     - Exporting and emailing are best-effort. Failures while creating or sending exports are logged and do
   *       not prevent the delete/archive from completing.
   *     - The response will include ``export_urls`` when files are saved and not directly returned.
   */
  v1_user_mang_me_destroy: {
    parameters: {
      query?: {
        /** @description 'delete' or 'archive' */
        action?: string;
        chat?: boolean;
        /** @description If true, returns a zip of CSV+PDF */
        download_now?: boolean;
        profile?: boolean;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UnifiedSyncDeleteResponse"];
        };
      };
      /** @description Invalid action or request */
      400: {
        content: never;
      };
      /** @description Auth required */
      401: {
        content: never;
      };
    };
  };
  /**
   * Partial profile update
   * @description Authenticated partial update for profile fields (me endpoint style).
   */
  v1_user_mang_me_partial_update: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProfileRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileRequest"];
        "multipart/form-data": components["schemas"]["PatchedProfileRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UnifiedSyncPatchResponse"];
        };
      };
      /** @description Validation error */
      400: {
        content: never;
      };
      /** @description Auth required */
      401: {
        content: never;
      };
    };
  };
}
